//go:build !ignore_autogenerated

/*
This file was generated with "make generate-deepcopy".
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeDefinition) DeepCopyInto(out *AttributeDefinition) {
	*out = *in
	if in.Enum != nil {
		in, out := &in.Enum, &out.Enum
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeDefinition.
func (in *AttributeDefinition) DeepCopy() *AttributeDefinition {
	if in == nil {
		return nil
	}
	out := new(AttributeDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExecProducer) DeepCopyInto(out *ExecProducer) {
	*out = *in
	in.Selector.DeepCopyInto(&out.Selector)
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(ProducerParams)
		(*in).DeepCopyInto(*out)
	}
	if in.Return != nil {
		in, out := &in.Return, &out.Return
		*out = make(map[AttributeName]ProducerReturnDefinition, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExecProducer.
func (in *ExecProducer) DeepCopy() *ExecProducer {
	if in == nil {
		return nil
	}
	out := new(ExecProducer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPProducer) DeepCopyInto(out *HTTPProducer) {
	*out = *in
	out.AuthSecret = in.AuthSecret
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(ProducerParams)
		(*in).DeepCopyInto(*out)
	}
	if in.Return != nil {
		in, out := &in.Return, &out.Return
		*out = make(map[AttributeName]ProducerReturnDefinition, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPProducer.
func (in *HTTPProducer) DeepCopy() *HTTPProducer {
	if in == nil {
		return nil
	}
	out := new(HTTPProducer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LocalSecretRef) DeepCopyInto(out *LocalSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LocalSecretRef.
func (in *LocalSecretRef) DeepCopy() *LocalSecretRef {
	if in == nil {
		return nil
	}
	out := new(LocalSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerParams) DeepCopyInto(out *ProducerParams) {
	*out = *in
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[AttributeName]AttributeDefinition, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Required != nil {
		in, out := &in.Required, &out.Required
		*out = make([]AttributeName, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerParams.
func (in *ProducerParams) DeepCopy() *ProducerParams {
	if in == nil {
		return nil
	}
	out := new(ProducerParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProducerReturnDefinition) DeepCopyInto(out *ProducerReturnDefinition) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProducerReturnDefinition.
func (in *ProducerReturnDefinition) DeepCopy() *ProducerReturnDefinition {
	if in == nil {
		return nil
	}
	out := new(ProducerReturnDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountProducer) DeepCopyInto(out *ServiceAccountProducer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountProducer.
func (in *ServiceAccountProducer) DeepCopy() *ServiceAccountProducer {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountProducer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceAccountProducer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountProducerAuthSecret) DeepCopyInto(out *ServiceAccountProducerAuthSecret) {
	*out = *in
	out.LocalSecretRef = in.LocalSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountProducerAuthSecret.
func (in *ServiceAccountProducerAuthSecret) DeepCopy() *ServiceAccountProducerAuthSecret {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountProducerAuthSecret)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountProducerList) DeepCopyInto(out *ServiceAccountProducerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceAccountProducer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountProducerList.
func (in *ServiceAccountProducerList) DeepCopy() *ServiceAccountProducerList {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountProducerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceAccountProducerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountProducerSpec) DeepCopyInto(out *ServiceAccountProducerSpec) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPProducer)
		(*in).DeepCopyInto(*out)
	}
	if in.Exec != nil {
		in, out := &in.Exec, &out.Exec
		*out = new(ExecProducer)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountProducerSpec.
func (in *ServiceAccountProducerSpec) DeepCopy() *ServiceAccountProducerSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountProducerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountProducerStatus) DeepCopyInto(out *ServiceAccountProducerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastExecution.DeepCopyInto(&out.LastExecution)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountProducerStatus.
func (in *ServiceAccountProducerStatus) DeepCopy() *ServiceAccountProducerStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountProducerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRequest) DeepCopyInto(out *ServiceAccountRequest) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRequest.
func (in *ServiceAccountRequest) DeepCopy() *ServiceAccountRequest {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRequest)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceAccountRequest) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRequestList) DeepCopyInto(out *ServiceAccountRequestList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ServiceAccountRequest, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRequestList.
func (in *ServiceAccountRequestList) DeepCopy() *ServiceAccountRequestList {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRequestList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ServiceAccountRequestList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRequestParams) DeepCopyInto(out *ServiceAccountRequestParams) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make(map[string][]string, len(*in))
		for key, val := range *in {
			var outVal []string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]string, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Args != nil {
		in, out := &in.Args, &out.Args
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRequestParams.
func (in *ServiceAccountRequestParams) DeepCopy() *ServiceAccountRequestParams {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRequestParams)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRequestSpec) DeepCopyInto(out *ServiceAccountRequestSpec) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalSecretRef)
		**out = **in
	}
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(ServiceAccountRequestParams)
		(*in).DeepCopyInto(*out)
	}
	if in.Rotation != nil {
		in, out := &in.Rotation, &out.Rotation
		*out = new(ServiceAccountRotation)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRequestSpec.
func (in *ServiceAccountRequestSpec) DeepCopy() *ServiceAccountRequestSpec {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRequestSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRequestStatus) DeepCopyInto(out *ServiceAccountRequestStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.LastRotation.DeepCopyInto(&out.LastRotation)
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(LocalSecretRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRequestStatus.
func (in *ServiceAccountRequestStatus) DeepCopy() *ServiceAccountRequestStatus {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRequestStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceAccountRotation) DeepCopyInto(out *ServiceAccountRotation) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceAccountRotation.
func (in *ServiceAccountRotation) DeepCopy() *ServiceAccountRotation {
	if in == nil {
		return nil
	}
	out := new(ServiceAccountRotation)
	in.DeepCopyInto(out)
	return out
}
