// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cloudogu/k8s-serviceaccount-lib/client/typed/api/v1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeApiV1 struct {
	*testing.Fake
}

func (c *FakeApiV1) ServiceAccountProducers(namespace string) v1.ServiceAccountProducerInterface {
	return newFakeServiceAccountProducers(c, namespace)
}

func (c *FakeApiV1) ServiceAccountRequests(namespace string) v1.ServiceAccountRequestInterface {
	return newFakeServiceAccountRequests(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeApiV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
