// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cloudogu/k8s-serviceaccount-lib/api/v1"
	apiv1 "github.com/cloudogu/k8s-serviceaccount-lib/client/typed/api/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeServiceAccountRequests implements ServiceAccountRequestInterface
type fakeServiceAccountRequests struct {
	*gentype.FakeClientWithList[*v1.ServiceAccountRequest, *v1.ServiceAccountRequestList]
	Fake *FakeApiV1
}

func newFakeServiceAccountRequests(fake *FakeApiV1, namespace string) apiv1.ServiceAccountRequestInterface {
	return &fakeServiceAccountRequests{
		gentype.NewFakeClientWithList[*v1.ServiceAccountRequest, *v1.ServiceAccountRequestList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("serviceaccountrequests"),
			v1.SchemeGroupVersion.WithKind("ServiceAccountRequest"),
			func() *v1.ServiceAccountRequest { return &v1.ServiceAccountRequest{} },
			func() *v1.ServiceAccountRequestList { return &v1.ServiceAccountRequestList{} },
			func(dst, src *v1.ServiceAccountRequestList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ServiceAccountRequestList) []*v1.ServiceAccountRequest {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.ServiceAccountRequestList, items []*v1.ServiceAccountRequest) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
