// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "github.com/cloudogu/k8s-serviceaccount-lib/api/v1"
	apiv1 "github.com/cloudogu/k8s-serviceaccount-lib/client/typed/api/v1"
	gentype "k8s.io/client-go/gentype"
)

// fakeServiceAccountProducers implements ServiceAccountProducerInterface
type fakeServiceAccountProducers struct {
	*gentype.FakeClientWithList[*v1.ServiceAccountProducer, *v1.ServiceAccountProducerList]
	Fake *FakeApiV1
}

func newFakeServiceAccountProducers(fake *FakeApiV1, namespace string) apiv1.ServiceAccountProducerInterface {
	return &fakeServiceAccountProducers{
		gentype.NewFakeClientWithList[*v1.ServiceAccountProducer, *v1.ServiceAccountProducerList](
			fake.Fake,
			namespace,
			v1.SchemeGroupVersion.WithResource("serviceaccountproducers"),
			v1.SchemeGroupVersion.WithKind("ServiceAccountProducer"),
			func() *v1.ServiceAccountProducer { return &v1.ServiceAccountProducer{} },
			func() *v1.ServiceAccountProducerList { return &v1.ServiceAccountProducerList{} },
			func(dst, src *v1.ServiceAccountProducerList) { dst.ListMeta = src.ListMeta },
			func(list *v1.ServiceAccountProducerList) []*v1.ServiceAccountProducer {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1.ServiceAccountProducerList, items []*v1.ServiceAccountProducer) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
