// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/api/v2"
	apiv2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/client/typed/api/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeServiceAccountRequests implements ServiceAccountRequestInterface
type fakeServiceAccountRequests struct {
	*gentype.FakeClientWithList[*v2.ServiceAccountRequest, *v2.ServiceAccountRequestList]
	Fake *FakeApiV2
}

func newFakeServiceAccountRequests(fake *FakeApiV2, namespace string) apiv2.ServiceAccountRequestInterface {
	return &fakeServiceAccountRequests{
		gentype.NewFakeClientWithList[*v2.ServiceAccountRequest, *v2.ServiceAccountRequestList](
			fake.Fake,
			namespace,
			v2.SchemeGroupVersion.WithResource("serviceaccountrequests"),
			v2.SchemeGroupVersion.WithKind("ServiceAccountRequest"),
			func() *v2.ServiceAccountRequest { return &v2.ServiceAccountRequest{} },
			func() *v2.ServiceAccountRequestList { return &v2.ServiceAccountRequestList{} },
			func(dst, src *v2.ServiceAccountRequestList) { dst.ListMeta = src.ListMeta },
			func(list *v2.ServiceAccountRequestList) []*v2.ServiceAccountRequest {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2.ServiceAccountRequestList, items []*v2.ServiceAccountRequest) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
