// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/api/v2"
	apiv2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/client/typed/api/v2"
	gentype "k8s.io/client-go/gentype"
)

// fakeServiceAccountProducers implements ServiceAccountProducerInterface
type fakeServiceAccountProducers struct {
	*gentype.FakeClientWithList[*v2.ServiceAccountProducer, *v2.ServiceAccountProducerList]
	Fake *FakeApiV2
}

func newFakeServiceAccountProducers(fake *FakeApiV2, namespace string) apiv2.ServiceAccountProducerInterface {
	return &fakeServiceAccountProducers{
		gentype.NewFakeClientWithList[*v2.ServiceAccountProducer, *v2.ServiceAccountProducerList](
			fake.Fake,
			namespace,
			v2.SchemeGroupVersion.WithResource("serviceaccountproducers"),
			v2.SchemeGroupVersion.WithKind("ServiceAccountProducer"),
			func() *v2.ServiceAccountProducer { return &v2.ServiceAccountProducer{} },
			func() *v2.ServiceAccountProducerList { return &v2.ServiceAccountProducerList{} },
			func(dst, src *v2.ServiceAccountProducerList) { dst.ListMeta = src.ListMeta },
			func(list *v2.ServiceAccountProducerList) []*v2.ServiceAccountProducer {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v2.ServiceAccountProducerList, items []*v2.ServiceAccountProducer) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
