// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/client/typed/api/v2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeApiV2 struct {
	*testing.Fake
}

func (c *FakeApiV2) ServiceAccountProducers(namespace string) v2.ServiceAccountProducerInterface {
	return newFakeServiceAccountProducers(c, namespace)
}

func (c *FakeApiV2) ServiceAccountRequests(namespace string) v2.ServiceAccountRequestInterface {
	return newFakeServiceAccountRequests(c, namespace)
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeApiV2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
