// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	http "net/http"

	apiv2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/api/v2"
	scheme "github.com/cloudogu/k8s-serviceaccount-lib/v2/client/scheme"
	rest "k8s.io/client-go/rest"
)

type ApiV2Interface interface {
	RESTClient() rest.Interface
	ServiceAccountProducersGetter
	ServiceAccountRequestsGetter
}

// ApiV2Client is used to interact with features provided by the api group.
type ApiV2Client struct {
	restClient rest.Interface
}

func (c *ApiV2Client) ServiceAccountProducers(namespace string) ServiceAccountProducerInterface {
	return newServiceAccountProducers(c, namespace)
}

func (c *ApiV2Client) ServiceAccountRequests(namespace string) ServiceAccountRequestInterface {
	return newServiceAccountRequests(c, namespace)
}

// NewForConfig creates a new ApiV2Client for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ApiV2Client, error) {
	config := *c
	setConfigDefaults(&config)
	httpClient, err := rest.HTTPClientFor(&config)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(&config, httpClient)
}

// NewForConfigAndClient creates a new ApiV2Client for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ApiV2Client, error) {
	config := *c
	setConfigDefaults(&config)
	client, err := rest.RESTClientForConfigAndClient(&config, h)
	if err != nil {
		return nil, err
	}
	return &ApiV2Client{client}, nil
}

// NewForConfigOrDie creates a new ApiV2Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ApiV2Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new ApiV2Client for the given RESTClient.
func New(c rest.Interface) *ApiV2Client {
	return &ApiV2Client{c}
}

func setConfigDefaults(config *rest.Config) {
	gv := apiv2.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = rest.CodecFactoryForGeneratedClient(scheme.Scheme, scheme.Codecs).WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *ApiV2Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
