// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	apiv2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/api/v2"
	scheme "github.com/cloudogu/k8s-serviceaccount-lib/v2/client/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServiceAccountProducersGetter has a method to return a ServiceAccountProducerInterface.
// A group's client should implement this interface.
type ServiceAccountProducersGetter interface {
	ServiceAccountProducers(namespace string) ServiceAccountProducerInterface
}

// ServiceAccountProducerInterface has methods to work with ServiceAccountProducer resources.
type ServiceAccountProducerInterface interface {
	Create(ctx context.Context, serviceAccountProducer *apiv2.ServiceAccountProducer, opts v1.CreateOptions) (*apiv2.ServiceAccountProducer, error)
	Update(ctx context.Context, serviceAccountProducer *apiv2.ServiceAccountProducer, opts v1.UpdateOptions) (*apiv2.ServiceAccountProducer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceAccountProducer *apiv2.ServiceAccountProducer, opts v1.UpdateOptions) (*apiv2.ServiceAccountProducer, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv2.ServiceAccountProducer, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv2.ServiceAccountProducerList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv2.ServiceAccountProducer, err error)
	ServiceAccountProducerExpansion
}

// serviceAccountProducers implements ServiceAccountProducerInterface
type serviceAccountProducers struct {
	*gentype.ClientWithList[*apiv2.ServiceAccountProducer, *apiv2.ServiceAccountProducerList]
}

// newServiceAccountProducers returns a ServiceAccountProducers
func newServiceAccountProducers(c *ApiV2Client, namespace string) *serviceAccountProducers {
	return &serviceAccountProducers{
		gentype.NewClientWithList[*apiv2.ServiceAccountProducer, *apiv2.ServiceAccountProducerList](
			"serviceaccountproducers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv2.ServiceAccountProducer { return &apiv2.ServiceAccountProducer{} },
			func() *apiv2.ServiceAccountProducerList { return &apiv2.ServiceAccountProducerList{} },
		),
	}
}
