// Code generated by client-gen. DO NOT EDIT.

package v2

import (
	context "context"

	apiv2 "github.com/cloudogu/k8s-serviceaccount-lib/v2/api/v2"
	scheme "github.com/cloudogu/k8s-serviceaccount-lib/v2/client/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServiceAccountRequestsGetter has a method to return a ServiceAccountRequestInterface.
// A group's client should implement this interface.
type ServiceAccountRequestsGetter interface {
	ServiceAccountRequests(namespace string) ServiceAccountRequestInterface
}

// ServiceAccountRequestInterface has methods to work with ServiceAccountRequest resources.
type ServiceAccountRequestInterface interface {
	Create(ctx context.Context, serviceAccountRequest *apiv2.ServiceAccountRequest, opts v1.CreateOptions) (*apiv2.ServiceAccountRequest, error)
	Update(ctx context.Context, serviceAccountRequest *apiv2.ServiceAccountRequest, opts v1.UpdateOptions) (*apiv2.ServiceAccountRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceAccountRequest *apiv2.ServiceAccountRequest, opts v1.UpdateOptions) (*apiv2.ServiceAccountRequest, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv2.ServiceAccountRequest, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv2.ServiceAccountRequestList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv2.ServiceAccountRequest, err error)
	ServiceAccountRequestExpansion
}

// serviceAccountRequests implements ServiceAccountRequestInterface
type serviceAccountRequests struct {
	*gentype.ClientWithList[*apiv2.ServiceAccountRequest, *apiv2.ServiceAccountRequestList]
}

// newServiceAccountRequests returns a ServiceAccountRequests
func newServiceAccountRequests(c *ApiV2Client, namespace string) *serviceAccountRequests {
	return &serviceAccountRequests{
		gentype.NewClientWithList[*apiv2.ServiceAccountRequest, *apiv2.ServiceAccountRequestList](
			"serviceaccountrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv2.ServiceAccountRequest { return &apiv2.ServiceAccountRequest{} },
			func() *apiv2.ServiceAccountRequestList { return &apiv2.ServiceAccountRequestList{} },
		),
	}
}
