// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	apiv1 "github.com/cloudogu/k8s-serviceaccount-lib/api/v1"
	scheme "github.com/cloudogu/k8s-serviceaccount-lib/client/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServiceAccountProducersGetter has a method to return a ServiceAccountProducerInterface.
// A group's client should implement this interface.
type ServiceAccountProducersGetter interface {
	ServiceAccountProducers(namespace string) ServiceAccountProducerInterface
}

// ServiceAccountProducerInterface has methods to work with ServiceAccountProducer resources.
type ServiceAccountProducerInterface interface {
	Create(ctx context.Context, serviceAccountProducer *apiv1.ServiceAccountProducer, opts metav1.CreateOptions) (*apiv1.ServiceAccountProducer, error)
	Update(ctx context.Context, serviceAccountProducer *apiv1.ServiceAccountProducer, opts metav1.UpdateOptions) (*apiv1.ServiceAccountProducer, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceAccountProducer *apiv1.ServiceAccountProducer, opts metav1.UpdateOptions) (*apiv1.ServiceAccountProducer, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.ServiceAccountProducer, error)
	List(ctx context.Context, opts metav1.ListOptions) (*apiv1.ServiceAccountProducerList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apiv1.ServiceAccountProducer, err error)
	ServiceAccountProducerExpansion
}

// serviceAccountProducers implements ServiceAccountProducerInterface
type serviceAccountProducers struct {
	*gentype.ClientWithList[*apiv1.ServiceAccountProducer, *apiv1.ServiceAccountProducerList]
}

// newServiceAccountProducers returns a ServiceAccountProducers
func newServiceAccountProducers(c *ApiV1Client, namespace string) *serviceAccountProducers {
	return &serviceAccountProducers{
		gentype.NewClientWithList[*apiv1.ServiceAccountProducer, *apiv1.ServiceAccountProducerList](
			"serviceaccountproducers",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1.ServiceAccountProducer { return &apiv1.ServiceAccountProducer{} },
			func() *apiv1.ServiceAccountProducerList { return &apiv1.ServiceAccountProducerList{} },
		),
	}
}
