// Code generated by client-gen. DO NOT EDIT.

package v1

import (
	context "context"

	apiv1 "github.com/cloudogu/k8s-serviceaccount-lib/api/v1"
	scheme "github.com/cloudogu/k8s-serviceaccount-lib/client/scheme"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// ServiceAccountRequestsGetter has a method to return a ServiceAccountRequestInterface.
// A group's client should implement this interface.
type ServiceAccountRequestsGetter interface {
	ServiceAccountRequests(namespace string) ServiceAccountRequestInterface
}

// ServiceAccountRequestInterface has methods to work with ServiceAccountRequest resources.
type ServiceAccountRequestInterface interface {
	Create(ctx context.Context, serviceAccountRequest *apiv1.ServiceAccountRequest, opts metav1.CreateOptions) (*apiv1.ServiceAccountRequest, error)
	Update(ctx context.Context, serviceAccountRequest *apiv1.ServiceAccountRequest, opts metav1.UpdateOptions) (*apiv1.ServiceAccountRequest, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, serviceAccountRequest *apiv1.ServiceAccountRequest, opts metav1.UpdateOptions) (*apiv1.ServiceAccountRequest, error)
	Delete(ctx context.Context, name string, opts metav1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts metav1.DeleteOptions, listOpts metav1.ListOptions) error
	Get(ctx context.Context, name string, opts metav1.GetOptions) (*apiv1.ServiceAccountRequest, error)
	List(ctx context.Context, opts metav1.ListOptions) (*apiv1.ServiceAccountRequestList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts metav1.PatchOptions, subresources ...string) (result *apiv1.ServiceAccountRequest, err error)
	ServiceAccountRequestExpansion
}

// serviceAccountRequests implements ServiceAccountRequestInterface
type serviceAccountRequests struct {
	*gentype.ClientWithList[*apiv1.ServiceAccountRequest, *apiv1.ServiceAccountRequestList]
}

// newServiceAccountRequests returns a ServiceAccountRequests
func newServiceAccountRequests(c *ApiV1Client, namespace string) *serviceAccountRequests {
	return &serviceAccountRequests{
		gentype.NewClientWithList[*apiv1.ServiceAccountRequest, *apiv1.ServiceAccountRequestList](
			"serviceaccountrequests",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1.ServiceAccountRequest { return &apiv1.ServiceAccountRequest{} },
			func() *apiv1.ServiceAccountRequestList { return &apiv1.ServiceAccountRequestList{} },
		),
	}
}
